# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-02 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0039_enrollment_anon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='anon_email',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
    ]
