# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-02 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0040_enrollment_anon_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='anon_email',
            field=models.CharField(blank=True, default='', max_length=85),
        ),
    ]
