# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-08 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0041_auto_20180502_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='anon_id',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
