# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-14 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0042_enrollment_anon_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='anon_email',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='anon_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
