# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-21 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0043_auto_20180514_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='anon_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
