# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-28 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_services', '0006_ltiservice_enable_api_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiservice',
            name='allow_real_user_data',
            field=models.BooleanField(default=False, help_text='Allow passing un-pseudonymised user data to the LTI service.'),
        ),
    ]
